# Generated by Django 4.2.4 on 2023-08-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order placed', 'order placed'), ('shipped', 'shipped'), ('order pending', 'order pending'), ('out for delivery', 'out for delivery'), ('order canceled', 'order canceled')], default='order placed', max_length=100),
        ),
    ]
