# Generated by Django 4.2.4 on 2023-08-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order placed', 'order placed'), ('shipped', 'shipped'), ('order pending', 'order pending'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered'), ('order canceled', 'order canceled')], default='order placed', max_length=100),
        ),
    ]
